const players = [
// ==============================
// ======= FORWARD PLAYERS =====
// ==============================


  {
    name: "SABBIR",
    number: 10,
    category: "forwards",
    image: "images/SABBIR.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 45,
      Goals: 40,
      Assists: 16,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 10,
    },
  },
  {
    name: "AKRAM",
    number: 21,
    category: "forwards",
    image: "images/AKRAM.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 5,
      Goals: 1,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
    {
    name: "RAZU",
    number: 11,
    category: "forwards",
    image: "images/RAZU.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 27,
      Goals: 2,
      Assists: 5,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
    {
    name: "JOY",
    number: 999,
    category: "forwards",
    image: "images/JOY.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 7,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
    {
    name: "ARIF",
    number: 999,
    category: "forwards",
    image: "images/ARIF.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 7,
      Goals: 2,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
      {
    name: "NAJIM",
    number: 7,
    category: "forwards",
    image: "images/NAJIM.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 25,
      Goals: 4,
      Assists: 3,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "AFFAN",
    number: 0,
    category: "forwards",
    image: "images/AFFAN.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 12,
      Goals: 2,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "ARIF T",
    number: 22,
    category: "forwards",
    image: "images/ARIF T.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 21,
      Goals: 3,
      Assists: 2,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "ANTOR",
    number: 21,
    category: "forwards",
    image: "images/ANTOR.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 8,
      Goals: 5,
      Assists: 2,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
   {
    name: "NASIM",
    number: 20,
    category: "forwards",
    image: "images/NASIM.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 14,
      Goals: 1,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "RAJON",
    number: 9,
    category: "forwards",
    image: "images/RAJON.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 16,
      Goals: 3,
      Assists: 2,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
   {
    name: "RAYEL",
    number: 30,
    category: "forwards",
    image: "images/RAYEL.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 8,
      Goals: 5,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "SAGOR",
    number: 25,
    category: "forwards",
    image: "images/SAGOR.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 5,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "KHOLIL",
    number: 19,
    category: "forwards",
    image: "images/KHOLIL.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 2,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "MASUM",
    number: 17,
    category: "forwards",
    image: "images/MASUM.jpg",
    video: "https://www.youtube.com/embed/1wVho3I0NtU",
    stats: {
      Position: "Forward",
      Appearances: 1,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
// ==============================
// ===== MIDFIELDER PLAYERS =====
// ==============================

  {
    name: "SHAJAN",
    number: 11,
    category: "midfielders",
    image: "images/SHAJAN.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 4,
      Goals: 1,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
 {
    name: "JAKARIYA",
    number: 16,
    category: "midfielders",
    image: "images/JAKARIYA.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 29,
      Goals: 4,
      Assists: 12,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 3,
    },
  },
  {
    name: "NASIR",
    number: 999,
    category: "midfielders",
    image: "images/NASIR.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 28,
      Goals: 4,
      Assists: 4,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
   {
    name: "JUNAID",
    number: 12,
    category: "midfielders",
    image: "images/JUNAID.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 10,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "JAKARIA",
    number: 7,
    category: "midfielders",
    image: "images/JAKARIA.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 18,
      Goals: 5,
      Assists: 3,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
  {
    name: "SHUVO",
    number: 999,
    category: "midfielders",
    image: "images/SHUVO.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 2,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "FOYSAL",
    number: 999,
    category: "midfielders",
    image: "images/FOYSAL.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 9,
      Goals: 2,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 2,
    },
  },
   {
    name: "OPI",
    number: 17,
    category: "midfielders",
    image: "images/OPI.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 9,
      Goals: 2,
      Assists: 5,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
  {
    name: "RUMEL",
    number: 12,
    category: "midfielders",
    image: "images/RUMEL.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 12,
      Goals: 4,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "RASEL",
    number: 8,
    category: "midfielders",
    image: "images/RASEL.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 10,
      Goals: 2,
      Assists: 2,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
  {
    name: "SAYMON",
    number: 999,
    category: "midfielders",
    image: "images/SAYMON.jpg",
    video: "https://www.youtube.com/embed/3qaF4tGvW9M",
    stats: {
      Position: "Midfielder",
      Appearances: 4,
      Goals: 0,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
// ============================
// ===== DEFENDER PLAYERS ====
// ============================

  {
    name: "SUHEL",
    number: 999,
    category: "defenders",
    image: "images/SUHEL.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 12,
      Goals: 1,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
 {
    name: "RAFI",
    number: 93,
    category: "defenders",
    image: "images/RAFI.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 32,
      Goals: 1,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
 {
    name: "SANI",
    number: 6,
    category: "defenders",
    image: "images/SANI.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 22,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "JANEL",
    number: 13,
    category: "defenders",
    image: "images/JANEL.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 4,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "BISHAL",
    number: 2,
    category: "defenders",
    image: "images/BISHAL.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 21,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "SHAHIN",
    number: 999,
    category: "defenders",
    image: "images/SHAHIN.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 10,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "EMON",
    number: 45,
    category: "defenders",
    image: "images/EMON.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 14,
      Goals: 0,
      Assists: 2,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "ASHIK",
    number: 5,
    category: "defenders",
    image: "images/ASHIK.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 14,
      Goals: 2,
      Assists: 1,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
  {
    name: "RAYHAN",
    number: 999,
    category: "defenders",
    image: "images/RAYHAN.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 14,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "ASHRAFUL",
    number: 3,
    category: "defenders",
    image: "images/ASHRAFUL.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 20,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "PIYAS",
    number: 999,
    category: "defenders",
    image: "images/PIYAS.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 5,
      Goals: 1,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "H.M SHAHIN",
    number: 14,
    category: "defenders",
    image: "images/H.M SHAHIN.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 12,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 1,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "MAHDI",
    number: 57,
    category: "defenders",
    image: "images/MAHDI.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 16,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 1,
    },
  },
   {
    name: "NAIM",
    number: 999,
    category: "defenders",
    image: "images/NAIM.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 1,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "FUHAD",
    number: 999,
    category: "defenders",
    image: "images/FUHAD.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 6,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
   {
    name: "SALMAN",
    number: 4,
    category: "defenders",
    image: "images/SALMAN.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 8,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "FARDIN",
    number: 4,
    category: "defenders",
    image: "images/FARDIN.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 4,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "SHAHRIAR",
    number: 4,
    category: "defenders",
    image: "images/SHAHRIAR.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 6,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "MUZAMMEL",
    number: 999,
    category: "defenders",
    image: "images/AMMEL.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 1,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
{
    name: "JOY K",
    number: 5,
    category: "defenders",
    image: "images/MUZAMMEL.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 7,
      Goals: 1,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
  {
    name: "RAJIB",
    number: 3,
    category: "defenders",
    image: "images/RAJIB.jpg",
    video: "https://www.youtube.com/embed/GLB93M_z9gk",
    stats: {
      Position: "Defender",
      Appearances: 1,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      MOTM: 0,
    },
  },
// ==============================
// ===== GOALKEEPER PLAYERS ====
// ==============================


  {
    name: "SHABUDDIN",
    number: 31,
    category: "goalkeepers",
    image: "images/SHABUDDIN.jpg",
    video: "https://www.youtube.com/embed/_PVRnKrcy3k",
    stats: {
      Position: "Goalkeeper",
      Appearances: 14,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      "Penalty Saves": 0,
      "Clean Sheets": 0,
      MOTM: 1,
    },
  },
  {
    name: "ROKI",
    number: 1,
    category: "goalkeepers",
    image: "images/ROKI.jpg",
    video: "https://www.youtube.com/embed/_PVRnKrcy3k",
    stats: {
      Position: "Goalkeeper",
      Appearances: 11,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      "Penalty Saves": 0,
      "Clean Sheets": 0,
      MOTM: 1,
    },
  },
   {
    name: "SUHAG",
    number: 23,
    category: "goalkeepers",
    image: "images/SUHAG.jpg",
    video: "https://www.youtube.com/embed/_PVRnKrcy3k",
    stats: {
      Position: "Goalkeeper",
      Appearances: 6,
      Goals: 0,
      Assists: 0,
      Interceptions: 0,
      Blocked: 0,
      "Successful Tackle": 0,
      "Yellow Cards": 0,
      "Red Cards": 0,
      "Penalty Saves": 0,
      "Clean Sheets": 0,
      MOTM: 0,
    },
  },
];


// =============== FUNCTIONAL CODE ===============

function calculateScore(stats) {
  const goal = stats.Goals || 0;
  const assist = stats.Assists || 0;
  const motm = stats.MOTM || 0;
  const yellow = stats["Yellow Cards"] || 0;
  const red = stats["Red Cards"] || 0;
  const tackle = stats["Successful Tackle"] || 0;
  const interception = stats.Interceptions || 0;
  const blocked = stats.Blocked || 0;

  return goal * 4 + assist * 3 + motm * 3 + tackle + interception + blocked - (yellow + red * 3);
}

function renderPlayers(category = "") {
  const container = document.getElementById("playersContainer");
  container.innerHTML = "";

  const filtered = players
    .filter((p) => !category || p.category === category)
    .sort((a, b) => calculateScore(b.stats) - calculateScore(a.stats));

  filtered.forEach((player) => {
    const card = document.createElement("div");
    card.className = "player-card";
    card.tabIndex = 0;
    card.innerHTML = `
      <img src="${player.image}" alt="${player.name}" class="player-img" onclick="playVideo('${player.video}')" />
      <div class="player-name">${player.name}</div>
      <div class="jersey-number"><strong>${player.number}</strong></div>
      <div class="stats">
        ${Object.entries(player.stats)
          .map(([k, v]) => `<div class="stat"><span>${k}</span><span>${v}</span></div>`)
          .join("")}
      </div>
    `;
    container.appendChild(card);
  });
}

function selectCategory(category) {
  document.querySelectorAll(".category-btn").forEach((btn) => {
    btn.setAttribute("aria-pressed", btn.textContent.toLowerCase() === category);
  });
  renderPlayers(category);
}

function searchPlayers() {
  const input = document.getElementById("searchInput").value.toLowerCase();
  const filtered = players
    .filter((player) => player.name.toLowerCase().includes(input))
    .sort((a, b) => calculateScore(b.stats) - calculateScore(a.stats));

  const container = document.getElementById("playersContainer");
  container.innerHTML = "";

  filtered.forEach((player) => {
    const card = document.createElement("div");
    card.className = "player-card";
    card.tabIndex = 0;
    card.innerHTML = `
      <img src="${player.image}" alt="${player.name}" class="player-img" onclick="playVideo('${player.video}')" />
      <div class="player-name">${player.name}</div>
      <div class="jersey-number"><strong>${player.number}</strong></div>
      <div class="stats">
        ${Object.entries(player.stats)
          .map(([k, v]) => `<div class="stat"><span>${k}</span><span>${v}</span></div>`)
          .join("")}
      </div>
    `;
    container.appendChild(card);
  });
}

function playVideo(url) {
  document.getElementById("overlay").classList.add("active");
  document.getElementById("videoContainer").innerHTML = `
    <iframe width="100%" height="360" src="${url}" frameborder="0" allowfullscreen></iframe>
  `;
  document.getElementById("overlay").focus();
}

function closeOverlay() {
  document.getElementById("overlay").classList.remove("active");
  document.getElementById("videoContainer").innerHTML = "";
}

// Initialize
renderPlayers();
